version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Core Rust Crate
  - package-ecosystem: "cargo"
    directory: "/core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Tauri App (Rust)
  - package-ecosystem: "cargo"
    directory: "/app/src-tauri"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Frontend (NPM)
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Analysis (NPM)
  - package-ecosystem: "npm"
    directory: "/analysis"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Analysis (Rust)
  - package-ecosystem: "cargo"
    directory: "/analysis/core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
